
@host = https://httpbin.org

###
GET {{host}}/get?x=123 HTTP/1.1
Accept: application/json

###
POST {{host}}/post HTTP/1.1
Content-Type: application/xml
Accept: application/json

<request>
    <name>sample</name>
    <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
</request>

###
POST {{host}}/post HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar

