= ITMX Product And Service
Junlapong L.
25 September 2017
:toc: right
:toclevels: 2

== Single Payment

=== เงื่อนไขการใช้บริการระบบ
เงื่อนไขการใช้บริการระบบ Single Payment แบ่งเป็น 2 กรณี ดังนี้

==== 1. กรณีเป็นธนาคาร

สามารถสมัครเป็นสมาชิกของ Single Payment System ใน Product ต่างๆ ที่บริษัทฯ เปิดให้บริการอยู่ เพื่อให้ความสะดวกกับลูกค้าของธนาคาร โดยมีข้อกำหนด ดังนี้

. เป็นธนาคารพาณิชย์ ตาม พระราชบัญญัติการธนาคารพาณิชย์ พ.ศ. 2505 หรือ
. เป็นสถาบันการเงินที่จัดตั้งโดยกฎหมายเฉพาะ

สำหรับเอกสารประกอบการสมัครหรือรายละเอียดต่างๆ นั้น สามารถติดต่อสอบถามได้โดยตรงจากบริษัทฯ ตามข้อมูลการติดต่อที่ให้ไว้ใน Website

==== 2. กรณีเป็นลูกค้าของธนาคาร

ลูกค้าของธนาคารต่างๆ ที่เป็นสมาชิกของ Single Payment System สามารถใช้บริการต่างๆ ของระบบนี้ได้ตาม Product ที่ธนาคารสมาชิกนั้นเป็นสมาชิกอยู่ เช่น

- การถอนเงินหรือสอบถามยอดระหว่างธนาคารผ่านเครื่อง ATM
- การโอนเงินระหว่างธนาคารผ่านเครื่อง ATM
- การโอนเงินระหว่างธนาคารผ่าน Counter สาขาของธนาคารต่างๆ หรือ
- การถอนเงินระหว่างประเทศผ่านเครื่อง ATM เป็นต้น

ซึ่งลูกค้าสามารถสอบถามรายละเอียดต่างๆ กับธนาคารที่ตนเองเป็นลูกค้าอยู่ได้โดยตรง

=== ประโยชน์ที่ได้รับ

ประโยชน์ที่ได้รับจากการใช้ระบบ Single Payment

==== ด้านธนาคารสมาชิก
ธนาคารสมาชิกประหยัดค่าลงทุน เช่น ไม่ต้องซื้อเครื่อง ATM หรือเพิ่มสาขาให้มากขึ้น เนื่องจากสามารถใช้เครื่อง ATM หรือ Counter ของธนาคารสมาชิกอื่น และยังเชื่อมโยงเครือข่ายการให้บริการ กับต่างประเทศได้ด้วย อีกทั้งธนาคารสมาชิก ไม่ต้องลงทุนจ้างเจ้าหน้าที่เพื่อให้บริการกับลูกค้ามากขึ้น
 
==== ด้านลูกค้าของธนาคาร
ลูกค้าของธนาคารสมาชิกสามารถทำธุรกรรมผ่านสื่ออิเล็กทรอนิกส์ ได้หลายช่องทาง เช่น เครื่อง ATM ของต่างธนาคารหรือต่างประเทศ Counter ของต่างธนาคาร อินเตอร์เน็ต หรือโทรศัพท์มือถือ เป็นต้น ซึ่งลูกค้าไม่ต้องเสียเวลาไปถึงสาขาของธนาคาร และไม่ต้องเสียเวลารอทั้งคิวเข้ารับบริการ รอเวลาธนาคารเปิดทำการ หรือรอให้ถึงวันทำการ อีกทั้งมีเวลาในการทำธุรกรรมต่างๆ มากขึ้น

== Local Switching System

=== ลักษณะบริการ

ITMX Local Switching สำหรับบัตรเอทีเอ็มและบัตรเดบิต เป็นบริการเชื่อมต่อระบบงานของบริษัทฯ กับระบบงานของธนาคารสมาชิก Switching โดยวิธีการส่งข้อมูลผ่านระบบคอมพิวเตอร์แบบออนไลน์ (On-Line) เพื่อทำ การรับ-ส่งรายการขออนุมัติการทำการตัดยอดเงินในบัญชีผู้ถือบัตรของธนาคารผู้ออกบัตร และบริการด้านอื่น ๆ ที่เกี่ยวข้องกับการชำระค่าสินค้า และ/หรือบริการ ณ จุดขายสินค้าและ/หรือบริการ โดยผ่านเครื่องรับบัตร (Electronic Data Capture – เครื่อง EDC) หรือบริการช่องทางอื่นๆ ของธนาคารเจ้าของเครื่อง โดยบริษัทฯ ทำหน้าที่ในการเป็นตัวกลางส่งผ่าน (Switching) รายการคำขออนุมัติและรายการอนุมัติการตัดยอดเงินดังกล่าว โดยระบบปัจจุบันใช้เฉพาะบัตร ATM และ/หรือบัตรเดบิต ที่ออกในประเทศไทยเพื่อชำระค่าสินค้า และ/หรือบริการผ่านธนาคารเจ้าของเครื่องในประเทศไทย รวมทั้งการให้บริการ Back Office เช่น ประมวลผลและชำระดุล กระบวนการคิดค่าธรรมเนียม การปฏิเสธการทำรายการ การปรับปรุงรายการ และการเรียกดูรายงาน ฯลฯ

=== เงื่อนไขการใช้บริการ

* กรณีเป็นธนาคารหรือสถาบันที่ประกอบธุรกิจให้บริการ การชำระค่าสินค้าและ/หรือบริการ
** เป็นผู้ประกอบธุรกิจที่จะต้องปฏิบัติตาม ประกาศ คณะกรรมการธุรกรรมทางอิเล็กทรอนิกส์ เรื่อง หลักเกณฑ์ วิธีการ และเงื่อนไขในการประกอบธุรกิจบริการ การชำระเงินทางอิเล็กทรอนิกส์(ฉบับที่ 2) พ.ศ. 2555

สำหรับเอกสารประกอบการสมัครหรือรายละเอียดต่างๆ นั้นสามารถติดต่อสอบถามได้โดยตรงจากบริษัทฯ ตามข้อมูลการติดต่อที่ให้ไว้ใน Website

* กรณีเป็นร้านค้าหรือผู้ให้บริการการชำระค่าสินค้าและ/หรือบริการ ณ จุดขาย (Point Of Sale)
** สามารถติดต่อสอบถามเงื่อนไขต่างๆ จากธนาคารหรือสถาบันที่ประกอบธุรกิจให้บริการ การชำระค่าสินค้าและ/หรือบริการ ได้โดยตรง

* กรณีเป็นลูกค้าหรือผู้ใช้บริการ การชำระค่าสินค้าและ/หรือบริการ
** เป็นลูกค้าที่มีบัตร ATM หรือบัตร Debit ซึ่งออกโดยธนาคารหรือสถาบันผู้ออกบัตรภายในประเทศ และมีการซื้อสินค้าและหรือบริการภายในประเทศ

รายละเอียดต่างๆ เกี่ยวกับการสมัครขอใช้บริการบัตรสามารถติดต่อสอบถามเงื่อนไขต่างๆ ได้จากธนาคารหรือสถาบันที่ออกบัตรได้โดยตรง

=== ประโยชน์ที่จะได้รับ

ประโยชน์ที่จะได้รับจากระบบ ITMX Local Switching

. ลูกค้าได้รับความสะดวกและปลอดภัย ลดการพกเงินสดสำหรับการใช้จ่ายเพื่อซื้อสินค้าหรือบริการ เนื่อง จากมีช่องทางการชำระเงินทางอิเล็กทรอนิกส์ ที่สามารถใช้แทนเงินสดได้เพิ่มขึ้น
. ลดต้นทุนการจัดการเงินสด เช่น การตรวจนับธนบัตร การขนส่ง/การจัดเก็บ/เติมเงิน ATM  ค่าจัดเก็บรักษาเงินสด ค่าประกันภัย เป็นต้น ของภาคการเงิน
. ลดความเสี่ยงจากธนบัตรปลอม
. ลดต้นทุนการให้บริการระบบการชำระเงินของธนาคาร โดยการใช้ระบบ Local Switching ที่มีอยู่แล้วในประเทศ
. ลดความเสี่ยงจากการพึ่งพาระบบการชำระเงินของต่างประเทศ

=== ความปลอดภัยของระบบ

ความปลอดภัยของระบบ ITMX Local Switching

บริษัทฯ ให้ความสำคัญในเรื่องความปลอดภัยสูงสุดของข้อมูล ที่ส่งผ่านสื่ออิเล็กทรอนิกส์ในระบบ Local Switching System โดยเน้นเทคโนโลยีที่มีความปลอดภัยสูงสุด และมีการเข้ารหัสข้อมูลตลอดเส้นทางการเชื่อมต่อ และผ่านอุปกรณ์ Network ระหว่างธนาคารสมาชิกกับบริษัทฯ แบบเครือข่ายเฉพาะ (Private Network) มีการควบคุมอุปกรณ์เชื่อมต่อด้วยระบบ Security Key โดยมุ่งเน้นให้ระบบ ชำระเงินผ่านบัตรมีความทันสมัย ปลอดภัยสูงสุดในระดับมาตรฐานสากล สามารถป้องกันมิให้ผู้อื่นเปลี่ยนแปลงแก้ไขข้อมูล ป้องกันการดักข้อมูล และสามารถรับรองความถูกต้องครบถ้วนของข้อมูลที่ส่งผ่านระบบ

ระบบ Local Switching ของบริษัทฯ ได้ผ่านการตรวจสอบและได้รับการรับรองมาตรฐาน `ISO 27001` (Information Security Management Systems) หรือระบบบริหารความมั่นคงปลอดภัยสารสนเทศ และได้ผ่านการรับรองการ Complied ตามมาตรฐาน `PCI DSS` (Payment Card Industry Data Security Standard)ซึ่งเป็นมาตรฐานด้านระบบรักษาความปลอดภัยของข้อมูลบัตรระดับสากลแล้ว

=== ธนาคารที่เป็นสมาชิก




== Introduction

[quote, Ben Parker, Spiderman Movie]
____
With great power comes great responsibility.
____

icon:comment[] This is a comment icon

icon:file[] And a file icon

icon:battery-full[] And a battery icon

Here are the other built-in admonition types:

NOTE: Some additional info...

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...


kbd:[Alt+F11] - Toggle Full Screen Mode in the Eclipse IDE

menu:View[Zoom > Reset]

Press the btn:[OK] button when you are finished.

== Basics

.This is the optional title of the table
|===
|Name of Column 1 |Name of Column 2

|Cell in column 1, row 1
|Cell in column 2, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|===


.Title
[cols="1,3",options="header"]
|===
|Name of Column 1 |Name of Column 2 |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

.with asciidoc elements
|===
|Keyboard shortcut |List |Note |Button

|kbd:[Ctrl+9]
a|* Test 1
* Test 2
* Test 3
a|
[NOTE]
====
This is a good idea
====
|btn:[OK]

|===


Before we dive in, let's first look at a few key thing to keep in mind when using the API.

=== CORS

Your API could be accessed from multiple clients. One of those could be a JavaScript web front-end, such as an AngularJS single page application.

When developing a JavaScript web front-end, you will have two choices:

. Put it in the same project, say inside _src/main/resources/static_, and deploy both the server and the client as a single unit.
. Keep it separate, say as a _Grunt_ project, and deploy it in a different domain. For example, your API could be hosted at `example.cfapps.io`, whereas your AngularJS application could be hosted at `www.example.com`.

If you go for the second option, your JavaScript can't call your API unless you deal with the https://en.wikipedia.org/wiki/Same-origin_policy[same origin policy].

Spring Lemon uses CORS at the server side to deal with this. You just have to add a line like this in _application.properties_:

----
lemon.cors.allowed-origins: http://localhost:9000,http://www.example.com
----

You may also need a little configuration at the client side. For example, in AngularJS, you will need to set the `withCredentials` flag of https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection[$http] service, like this:

Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

==== CSRF

_CSRF_ is a well known security vulnerability. If you do not know about it, http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#csrf[Spring Security reference material] explains it beautifully.

To handle CSRF, Spring Lemon sends a token to the client in each response. The token is sent as a cookie, named `XSRF-TOKEN`. Then, in each `PATCH`, `POST`, `PUT` or `DELETE` request, it expects the same token as a header named `X-XSRF-TOKEN`. An exception is thrown if the tokens do not match.

So, your client application should first send a GET request for getting the token, and then use that in POST kind of requests. Also, be aware that Spring Security removes or changes the cookie after certain events, like _logout_. Hence, after these events, your client application will again need to send some GET request and get the new token. Ping (see below) can be used for this.

When wrong CSRF token is sent, the response looks like this:

[source,json]
----
HTTP/1.1 403 Forbidden

{
    "status": 403,
    "error": "Forbidden",
    "message": "Expected CSRF token not found. Has your session expired?",
    "path": "/accessed_url"
}
----

Refer https://github.com/naturalprogrammer/spring-lemon#documentation-and-resources[documentation and resources] for more details.

===== CSRF and AngularJS

If your AngularJS client resides in the same project, say inside _src/main/resources/static_, you don't have to do anything special for CSRF. When sending a request, the https://docs.angularjs.org/api/ng/service/$http#cross-site-request-forgery-xsrf-protection[$http] service of AngularJS automatically puts the value of the `XSRF-TOKEN` cookie in a header named `X-XSRF-TOKEN`.

If you have the client as a separate project that is to be hosted separately though, you will have to add the header on your own. The easiest way to do it is to write an AngularJS _$http interceptor_, like this:


== Encryption

Message encryption with `AES 256 CBC mode` by `secret_key`

== Web 
=== Register
==== Endpoint

`{base_url}/kda-web/register`

==== POST Parameter
